[package]
name = "solana_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
solana-sdk = { version = "2.1.0", default-features = false }
solana-program = { version = "2.1.0", default-features = false }
bincode = "1.3.3"
hex = "0.4.3"
