[package]
name = "evm_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
bincode = "1.3.3"
hex = "0.4.3"
serde_json = "1.0"
alloy-rlp = { version = "0.3.11", default-features = false }
alloy-consensus = { version = "0.13.0", default-features = false }
# allow rand feature to be on the safe side
alloy-primitives = { version = "0.8.25", default-features = false, features = [
  "rand",
] }
alloy-sol-types = { version = "0.8.25", default-features = false }
alloy-json-abi = { version = "0.8.25", default-features = false }