[package]
name = "solana_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
solana-sdk = "2.0.3"
solana-program = "2.0.3"
bincode = "1.3.3"
hex = "0.4.3"
serde_json = "1.0"
solana_idl = "0.2.0"
serde = "1.0.219"
sha2 = { version = "0.10.8", default-features = false }
