[package]
name = "solana_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
solana-sdk = "2.0.3"
solana-program = "2.0.3"
bincode = "1.3.3"
hex = "0.4.3"
base64 = "0.13.0"
clap = "4.5.31"