pub const IDL_DB: [(&str, &str, &str); 13] = [
    ("Ape Pro", "JSW99DKmxNyREQM14SQLDykeBvEUG63TeohrvmofEiw", "ape_pro.json"),
    ("Metaplex Candy Machine", "cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ", "cndy.json"),
    ("Drift Protocol V2", "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH", "drift.json"),
    ("Jupiter Limit", "j1o2qRpjcyUwEvwtcfhEQefh773ZgjxcVRry7LDqg5X", "jupiter_limit.json"),
    ("Jupiter Swap", "JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB", "jupiter.json"),
    ("Kamino", "6LtLpnUFNByNXLyCoK9wA2MykKAmQNZKBdY8s47dehDc", "kamino.json"),
    ("Lifinity Swap V2", "2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c", "lifinity.json"),
    ("Meteora", "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo", "meteora.json"),
    ("Openbook", "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb", "openbook.json"),
    ("Orca Whirlpool", "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc", "orca.json"),
    ("Raydium", "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C", "raydium.json"),
    ("Stabble", "swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ", "stabble.json"),
    ("Jupiter Aggregator V6", "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4", "jupiter_agg_v6.json"),
];